services:
  - type: web
    name: notes-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p templates
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.0
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src
      sizeGB: 1 